import type { CountryCode, CountryConfig } from '@/types/country';

export const countries: Record<CountryCode, CountryConfig> = {
  de: {
    code: 'de',
    name: 'Germany',
    center: [10.45, 51.16],
    defaultZoom: 6,
    overviewDigits: 2,
    postcodeLength: 5,
    postcodeFormat: /^\d{5}$/,
    detailPath: '/data/de/plz5.geojson',
    overviewPath: '/data/de/plz2.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  nl: {
    code: 'nl',
    name: 'Netherlands',
    center: [5.29, 52.13],
    defaultZoom: 7,
    overviewDigits: 2,
    postcodeLength: 4,
    postcodeFormat: /^\d{4}$/,
    detailPath: '/data/nl/pc4.geojson',
    overviewPath: '/data/nl/pc2.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  fr: {
    code: 'fr',
    name: 'France',
    center: [2.21, 46.23],
    defaultZoom: 6,
    overviewDigits: 2,
    postcodeLength: 2,
    postcodeFormat: /^\d{2}[AB]?$/,
    detailPath: '/data/fr/dept.geojson',
    overviewPath: '/data/fr/regions.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  be: {
    code: 'be',
    name: 'Belgium',
    center: [4.47, 50.5],
    defaultZoom: 8,
    overviewDigits: 2,
    postcodeLength: 4,
    postcodeFormat: /^\d{4}$/,
    detailPath: '/data/be/pc4.geojson',
    overviewPath: '/data/be/pc2.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  dk: {
    code: 'dk',
    name: 'Denmark',
    center: [9.5, 56.26],
    defaultZoom: 7,
    overviewDigits: 2,
    postcodeLength: 4,
    postcodeFormat: /^\d{4}$/,
    detailPath: '/data/dk/post4.geojson',
    overviewPath: '/data/dk/post2.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  at: {
    code: 'at',
    name: 'Austria',
    center: [13.34, 47.7],
    defaultZoom: 7,
    overviewDigits: 3,
    postcodeLength: 4,
    postcodeFormat: /^\d{4}$/,
    detailPath: '/data/at/plz4.geojson',
    overviewPath: '/data/at/plz1.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  cz: {
    code: 'cz',
    name: 'Czechia',
    center: [15.47, 49.82],
    defaultZoom: 7,
    overviewDigits: 2,
    postcodeLength: 5,
    postcodeFormat: /^\d{3,5}$/,
    detailPath: '/data/cz/okres.geojson',
    overviewPath: '/data/cz/region.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  pl: {
    code: 'pl',
    name: 'Poland',
    center: [19.15, 51.92],
    defaultZoom: 6,
    overviewDigits: 2,
    postcodeLength: 5,
    postcodeFormat: /^\d{2}-\d{3}$/,
    detailPath: '/data/pl/detail.geojson',
    overviewPath: '/data/pl/overview.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  hu: {
    code: 'hu',
    name: 'Hungary',
    center: [19.5, 47.16],
    defaultZoom: 7,
    overviewDigits: 2,
    postcodeLength: 4,
    postcodeFormat: /^\d{4}$/,
    detailPath: '/data/hu/detail.geojson',
    overviewPath: '/data/hu/overview.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  ro: {
    code: 'ro',
    name: 'Romania',
    center: [24.97, 45.94],
    defaultZoom: 6,
    overviewDigits: 2,
    postcodeLength: 6,
    postcodeFormat: /^\d{6}$/,
    detailPath: '/data/ro/detail.geojson',
    overviewPath: '/data/ro/overview.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  it: {
    code: 'it',
    name: 'Italy',
    center: [12.57, 41.87],
    defaultZoom: 6,
    overviewDigits: 2,
    postcodeLength: 5,
    postcodeFormat: /^\d{5}$/,
    detailPath: '/data/it/detail.geojson',
    overviewPath: '/data/it/overview.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  sk: {
    code: 'sk',
    name: 'Slovakia',
    center: [19.7, 48.67],
    defaultZoom: 7,
    overviewDigits: 2,
    postcodeLength: 5,
    postcodeFormat: /^\d{3}\s?\d{2}$/,
    detailPath: '/data/sk/detail.geojson',
    overviewPath: '/data/sk/overview.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
};

export const enabledCountries: CountryCode[] = ['de', 'nl', 'fr', 'be', 'dk', 'at', 'cz', 'sk', 'pl', 'hu', 'ro', 'it'];

export const defaultCountry: CountryCode = 'de';
