import type { CountryCode, CountryConfig } from '@/types/country';

export const countries: Record<CountryCode, CountryConfig> = {
  de: {
    code: 'de',
    name: 'Germany',
    center: [10.45, 51.16],
    defaultZoom: 6,
    overviewDigits: 2,
    postcodeLength: 5,
    postcodeFormat: /^\d{5}$/,
    detailPath: '/data/de/plz5.geojson',
    overviewPath: '/data/de/plz2.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 11,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  nl: {
    code: 'nl',
    name: 'Netherlands',
    center: [5.29, 52.13],
    defaultZoom: 7,
    overviewDigits: 2,
    postcodeLength: 4,
    postcodeFormat: /^\d{4}$/,
    detailPath: '/data/nl/pc4.geojson',
    overviewPath: '/data/nl/pc2.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  fr: {
    code: 'fr',
    name: 'France',
    center: [2.21, 46.23],
    defaultZoom: 6,
    overviewDigits: 2,
    postcodeLength: 2,
    postcodeFormat: /^\d{2}[AB]?$/,
    detailPath: '/data/fr/dept.geojson',
    overviewPath: '/data/fr/regions.geojson',
    overviewZoomThreshold: 8,
    detailLabelMinZoom: 9,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  be: {
    code: 'be',
    name: 'Belgium',
    center: [4.47, 50.5],
    defaultZoom: 8,
    overviewDigits: 2,
    postcodeLength: 4,
    postcodeFormat: /^\d{4}$/,
    detailPath: '/data/be/pc4.geojson',
    overviewPath: '/data/be/pc2.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  dk: {
    code: 'dk',
    name: 'Denmark',
    center: [9.5, 56.26],
    defaultZoom: 7,
    overviewDigits: 2,
    postcodeLength: 4,
    postcodeFormat: /^\d{4}$/,
    detailPath: '/data/dk/post4.geojson',
    overviewPath: '/data/dk/post2.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  at: {
    code: 'at',
    name: 'Austria',
    center: [13.34, 47.7],
    defaultZoom: 7,
    overviewDigits: 3,
    postcodeLength: 5,
    postcodeFormat: /^\d{5}$/,
    detailPath: '/data/at/plz4.geojson',
    overviewPath: '/data/at/plz1.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 10,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
  cz: {
    code: 'cz',
    name: 'Czechia',
    center: [15.47, 49.82],
    defaultZoom: 7,
    overviewDigits: 2,
    postcodeLength: 5,
    postcodeFormat: /^\d{3,5}$/,
    detailPath: '/data/cz/okres.geojson',
    overviewPath: '/data/cz/region.geojson',
    overviewZoomThreshold: 9,
    detailLabelMinZoom: 7,
    detailPropertyKey: 'plz5',
    overviewPropertyKey: 'plz2',
  },
};

export const enabledCountries: CountryCode[] = ['de', 'nl', 'fr', 'be', 'dk', 'at', 'cz'];

export const defaultCountry: CountryCode = 'de';
