export const DE_REGION_LABELS: Record<string, string> = {
  '01': 'Dresden',
  '02': 'Cottbus',
  '03': 'Cottbus',
  '04': 'Leipzig',
  '06': 'Halle',
  '07': 'Gera',
  '08': 'Zwickau',
  '09': 'Chemnitz',
  '10': 'Berlin',
  '12': 'Berlin',
  '13': 'Berlin',
  '14': 'Potsdam',
  '15': 'Frankfurt (Oder)',
  '16': 'Oranienburg',
  '17': 'Neubrandenburg',
  '18': 'Rostock',
  '19': 'Schwerin',
  '20': 'Hamburg',
  '21': 'Hamburg / Lüneburg',
  '22': 'Hamburg',
  '23': 'Lübeck',
  '24': 'Kiel',
  '25': 'Itzehoe',
  '26': 'Oldenburg',
  '27': 'Bremen / Bremerhaven',
  '28': 'Bremen',
  '29': 'Celle',
  '30': 'Hannover',
  '31': 'Hannover',
  '32': 'Herford',
  '33': 'Bielefeld',
  '34': 'Kassel',
  '35': 'Gießen',
  '36': 'Fulda',
  '37': 'Göttingen',
  '38': 'Braunschweig',
  '39': 'Magdeburg',
  '40': 'Düsseldorf',
  '41': 'Mönchengladbach',
  '42': 'Wuppertal',
  '44': 'Dortmund',
  '45': 'Essen',
  '46': 'Oberhausen',
  '47': 'Duisburg',
  '48': 'Münster',
  '49': 'Osnabrück',
  '50': 'Köln',
  '51': 'Köln',
  '52': 'Aachen',
  '53': 'Bonn',
  '54': 'Trier',
  '55': 'Mainz',
  '56': 'Koblenz',
  '57': 'Siegen',
  '58': 'Hagen',
  '59': 'Hamm',
  '60': 'Frankfurt am Main',
  '61': 'Bad Homburg',
  '63': 'Offenbach / Aschaffenburg',
  '64': 'Darmstadt',
  '65': 'Wiesbaden',
  '66': 'Saarbrücken',
  '67': 'Ludwigshafen',
  '68': 'Mannheim',
  '69': 'Heidelberg',
  '70': 'Stuttgart',
  '71': 'Böblingen',
  '72': 'Tübingen',
  '73': 'Göppingen',
  '74': 'Heilbronn',
  '75': 'Pforzheim',
  '76': 'Karlsruhe',
  '77': 'Offenburg',
  '78': 'Villingen-Schwenningen',
  '79': 'Freiburg',
  '80': 'München',
  '81': 'München',
  '82': 'Starnberg',
  '83': 'Rosenheim',
  '84': 'Landshut',
  '85': 'Freising / Ingolstadt',
  '86': 'Augsburg',
  '87': 'Kempten',
  '88': 'Friedrichshafen',
  '89': 'Ulm',
  '90': 'Nürnberg',
  '91': 'Erlangen',
  '92': 'Amberg',
  '93': 'Regensburg',
  '94': 'Deggendorf',
  '95': 'Hof',
  '96': 'Bamberg',
  '97': 'Würzburg',
  '98': 'Suhl',
  '99': 'Erfurt',
};
