export const NL_REGION_LABELS: Record<string, string> = {
  '10': 'Amsterdam',
  '11': 'Amsterdam',
  '12': 'Haarlem',
  '13': 'Amersfoort',
  '14': 'Hilversum',
  '15': 'Alkmaar',
  '16': 'Hoorn / Purmerend',
  '17': 'Den Helder',
  '18': 'Lelystad',
  '19': 'Hoofddorp',
  '20': 'Den Haag',
  '21': 'Den Haag',
  '22': 'Delft / Leiden',
  '23': 'Leiden',
  '24': 'Katwijk / Alphen',
  '25': 'Zoetermeer',
  '26': 'Gouda',
  '27': 'Dordrecht',
  '28': 'Gorinchem',
  '29': 'Rotterdam',
  '30': 'Rotterdam',
  '31': 'Rotterdam / Schiedam',
  '32': 'Spijkenisse',
  '33': 'Brielle / Hellevoetsluis',
  '34': 'Middelburg / Vlissingen',
  '35': 'Terneuzen',
  '36': 'Bergen op Zoom',
  '37': 'Roosendaal',
  '38': 'Breda',
  '39': 'Oosterhout',
  '40': 'Eindhoven',
  '41': 'Eindhoven / Helmond',
  '42': 'Waalwijk',
  '43': 'Den Bosch',
  '44': 'Oss',
  '45': 'Tilburg',
  '46': 'Boxtel / Veghel',
  '47': 'Venlo',
  '48': 'Venray / Roermond',
  '49': 'Weert',
  '50': 'Maastricht',
  '51': 'Maastricht',
  '52': 'Sittard',
  '53': 'Kerkrade / Heerlen',
  '54': 'Geleen',
  '55': 'Vaals',
  '56': 'Echt',
  '57': 'Venlo',
  '58': 'Roermond',
  '59': 'Tegelen',
  '60': 'Arnhem',
  '61': 'Arnhem',
  '62': 'Wageningen',
  '63': 'Nijmegen',
  '64': 'Nijmegen / Tiel',
  '65': 'Ede',
  '66': 'Barneveld',
  '67': 'Doetinchem',
  '68': 'Winterswijk',
  '69': 'Zevenaar',
  '70': 'Utrecht',
  '71': 'Utrecht',
  '72': 'Veenendaal',
  '73': 'Woerden',
  '74': 'IJsselstein',
  '75': 'Amersfoort',
  '76': 'Soest / Baarn',
  '77': 'Bunschoten',
  '78': 'Almere',
  '79': 'Weesp / Bussum',
  '80': 'Zwolle',
  '81': 'Deventer',
  '82': 'Apeldoorn',
  '83': 'Harderwijk',
  '84': 'Kampen',
  '85': 'Meppel / Steenwijk',
  '86': 'Emmeloord',
  '87': 'Olst / Raalte',
  '88': 'Lelystad',
  '89': 'Hattem',
  '90': 'Groningen',
  '91': 'Delfzijl',
  '92': 'Hoogezand',
  '93': 'Stadskanaal',
  '94': 'Veendam',
  '95': 'Assen',
  '96': 'Emmen',
  '97': 'Hoogeveen',
  '98': 'Leeuwarden',
  '99': 'Drachten / Heerenveen',
};
